sudo: required

language: java
dist: trusty

jdk:
- openjdk8

services:
  - docker

before_install:
  - docker build -t catalogue/dockerfileCatalogue .
  - docker run -d -p 127.0.0.1:80:4567 catalogue/dockerfileCatalogue /bin/sh -c "cd /root/dockerfileCatalogue; bundle exec foreman start;"
  - docker ps -a
  - docker run catalogue/dockerfileCatalogue /bin/sh -c "cd /root/dockerfileCatalogue; bundle exec rake test"

script:
  - bundle exec rake test
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push USER/REPO;
    fi